[package]
name = "wgpu_audio_spectrogram_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
bytemuck = { version = "1.24", features = ["aarch64_simd", "derive"] }
cpal = "0.16"
image = "0.25"
pollster = "0.4"
ringbuf = "0.4"
wgpu = "28.0"
winit = "0.30"
